### ISSUE TITLE
File Dialog Box  is unreadeable when selecting documents, photos, videos 

### ISSUE THREAD

**Issue by ceyhunn** [bcalik/Whatsapp-Desktop#45] opened 2017-06-10 12:29 UTC
Whatsapp-Desktop version - latest
![screenshot from 2017-06-10 16-22-56](https://user-images.githubusercontent.com/5506156/27002737-dcf9cc2c-4df9-11e7-8c5a-dfdabe497d87.png)

**Comment by Enrico204** [comment] 2017-06-11 09:13
Which OS are you using (it seems Ubuntu) and which version? What's your system language/locale?

**Comment by ceyhunn** [comment] 2017-06-11 09:49
Hi, @Enrico204 
Manjaro GNOME edition -17.0.1
Gnome version - 3.24.2
Whatsapp-desktop - latest from AUR
LANG=en_US.UTF-8   in /etc/locale.conf as system locale

**Comment by Enrico204** [comment] 2017-06-11 17:41
Hi @ceyhunnabiyev 
I've installed Manjaro (same versions) and the problem is gone with latest code. It has been fixed in PR #46 (unfortunately after v0.3.3 that is the latest stable release).

You can check out the latest code from this repo or wait for a new release from @bcalik and/or @bil-elmoussaoui (for AUR).

**Comment by bilelmoussaoui** [comment] 2017-06-11 17:46
I will push a new update to the AUR package once there's a new release !

**Comment by ceyhunn** [comment] 2017-06-11 18:58
Thanks for your answers!!! 
@bcalik, It will be  pleasant for me if you make new release out, because I can't  download or upload any file in it.

**Comment by Enrico204** [comment] 2017-06-21 11:31
@ceyhunnabiyev @bil-elmoussaoui Due to #42 and the fact that @bcalik has no more time to dedicate to this project, I'll continue on my fork: https://github.com/Enrico204/Whatsapp-Desktop

**Closed as completed by Enrico204** 2017-06-21 11:31 UTC
